export const COMMON_CONDITIONS = [
  { name: 'POTS (Postural Orthostatic Tachycardia Syndrome)', description: 'Dysautonomia condition affecting blood flow' },
  { name: 'Chronic Fatigue Syndrome', description: 'Long-term fatigue not improved by rest' },
  { name: 'Fibromyalgia', description: 'Chronic widespread pain and tenderness' },
  { name: 'Migraine', description: 'Recurring severe headaches' },
  { name: 'IBS (Irritable Bowel Syndrome)', description: 'Digestive system disorder' },
  { name: 'Chronic Pain', description: 'Persistent pain lasting weeks to years' },
  { name: 'Anxiety', description: 'Persistent worry and nervousness' },
  { name: 'Depression', description: 'Persistent low mood and loss of interest' },
  { name: 'Insomnia', description: 'Difficulty falling or staying asleep' },
  { name: 'Arthritis', description: 'Joint inflammation and pain' },
  { name: 'Back Pain', description: 'Pain in the back or spine area' },
  { name: 'Headache', description: 'Pain in the head or upper neck' },
  { name: 'Dizziness', description: 'Feeling lightheaded or unsteady' },
  { name: 'Fatigue', description: 'Extreme tiredness or lack of energy' },
  { name: 'Brain Fog', description: 'Difficulty with focus and memory' },
  { name: 'Nausea', description: 'Feeling sick to the stomach' },
  { name: 'Heart Palpitations', description: 'Awareness of heartbeat' },
  { name: 'Muscle Pain', description: 'Soreness or aching in muscles' },
  { name: 'Joint Pain', description: 'Discomfort in joints' },
  { name: 'Sleep Issues', description: 'Problems with sleep quality or duration' },
  { name: 'Stress', description: 'Mental or emotional strain' },
  { name: 'Asthma', description: 'Breathing difficulty and airway inflammation' },
  { name: 'Allergies', description: 'Immune system reactions to substances' },
  { name: 'Eczema', description: 'Itchy, inflamed skin condition' },
  { name: 'GERD (Acid Reflux)', description: 'Stomach acid flowing back into esophagus' },
  { name: 'Endometriosis', description: 'Tissue similar to uterine lining grows outside uterus' },
  { name: 'PCOS (Polycystic Ovary Syndrome)', description: 'Hormonal disorder affecting ovaries' },
  { name: 'Hypothyroidism', description: 'Underactive thyroid gland' },
  { name: 'Hyperthyroidism', description: 'Overactive thyroid gland' },
  { name: 'Celiac Disease', description: 'Immune reaction to eating gluten' },
  { name: 'Lactose Intolerance', description: 'Inability to digest lactose' },
  { name: 'Crohns Disease', description: 'Inflammatory bowel disease' },
  { name: 'Ulcerative Colitis', description: 'Inflammatory bowel disease affecting colon' },
  { name: 'Psoriasis', description: 'Skin cells build up forming scales' },
  { name: 'Rosacea', description: 'Facial redness and visible blood vessels' },
  { name: 'TMJ (Temporomandibular Joint Disorder)', description: 'Jaw joint and muscle problems' },
  { name: 'Restless Leg Syndrome', description: 'Urge to move legs, especially at night' },
  { name: 'Sleep Apnea', description: 'Breathing repeatedly stops during sleep' },
  { name: 'Vertigo', description: 'Spinning sensation or dizziness' },
  { name: 'Tinnitus', description: 'Ringing or buzzing in ears' },
  { name: 'Carpal Tunnel Syndrome', description: 'Hand and arm numbness or tingling' },
  { name: 'Sciatica', description: 'Pain along sciatic nerve path' },
  { name: 'Plantar Fasciitis', description: 'Heel and bottom of foot pain' },
  { name: 'Tendonitis', description: 'Tendon inflammation' },
  { name: 'Bursitis', description: 'Joint bursa inflammation' },
  { name: 'Raynauds Syndrome', description: 'Reduced blood flow to fingers and toes' },
  { name: 'Lupus', description: 'Autoimmune disease affecting multiple organs' },
  { name: 'Rheumatoid Arthritis', description: 'Autoimmune joint inflammation' },
  { name: 'Multiple Sclerosis', description: 'Immune system attacks nerve coverings' },
  { name: 'Parkinsons Disease', description: 'Progressive nervous system disorder' },
  { name: 'Diabetes Type 1', description: 'Body does not produce insulin' },
  { name: 'Diabetes Type 2', description: 'Body resists insulin effects' },
  { name: 'High Blood Pressure', description: 'Elevated blood pressure levels' },
  { name: 'Low Blood Pressure', description: 'Below normal blood pressure' },
  { name: 'Anemia', description: 'Lack of healthy red blood cells' },
  { name: 'Vitamin D Deficiency', description: 'Insufficient vitamin D levels' },
  { name: 'Iron Deficiency', description: 'Low iron levels in body' },
  { name: 'Dehydration', description: 'Insufficient water in body' },
  { name: 'Seasonal Affective Disorder', description: 'Depression related to seasons' },
  { name: 'PTSD (Post-Traumatic Stress Disorder)', description: 'Trauma-related mental health condition' },
  { name: 'OCD (Obsessive-Compulsive Disorder)', description: 'Unwanted repetitive thoughts and behaviors' },
  { name: 'ADHD (Attention Deficit Hyperactivity Disorder)', description: 'Difficulty with attention and hyperactivity' },
  { name: 'Autism Spectrum Disorder', description: 'Developmental condition affecting communication' },
  { name: 'Bipolar Disorder', description: 'Extreme mood swings' },
  { name: 'Panic Disorder', description: 'Recurring panic attacks' },
  { name: 'Social Anxiety', description: 'Fear of social situations' },
  { name: 'Agoraphobia', description: 'Fear of situations causing panic' },
  { name: 'Chronic Sinusitis', description: 'Long-term sinus inflammation' },
  { name: 'Interstitial Cystitis', description: 'Chronic bladder pain' },
  { name: 'Overactive Bladder', description: 'Sudden urge to urinate' },
  { name: 'Gastroparesis', description: 'Delayed stomach emptying' },
  { name: 'Cyclic Vomiting Syndrome', description: 'Episodes of severe nausea and vomiting' },
  { name: 'Mast Cell Activation Syndrome', description: 'Mast cells release excessive chemicals' },
  { name: 'Ehlers-Danlos Syndrome', description: 'Connective tissue disorder' },
  { name: 'Chronic Lyme Disease', description: 'Persistent symptoms after Lyme infection' },
  { name: 'Long COVID', description: 'Persistent symptoms after COVID-19' },
  { name: 'Chronic Bronchitis', description: 'Long-term lung inflammation' },
  { name: 'COPD (Chronic Obstructive Pulmonary Disease)', description: 'Progressive lung disease' },
  { name: 'Scoliosis', description: 'Sideways curvature of spine' },
  { name: 'Herniated Disc', description: 'Spinal disc pushes out of place' },
  { name: 'Osteoporosis', description: 'Weak and brittle bones' },
  { name: 'Vitamin B12 Deficiency', description: 'Low B12 levels' },
  { name: 'Magnesium Deficiency', description: 'Insufficient magnesium levels' },
  { name: 'Hormone Imbalance', description: 'Irregular hormone levels' },
  { name: 'Perimenopause', description: 'Transition before menopause' },
  { name: 'Menopause Symptoms', description: 'Symptoms during menopause' },
  { name: 'PMS (Premenstrual Syndrome)', description: 'Symptoms before menstruation' },
  { name: 'PMDD (Premenstrual Dysphoric Disorder)', description: 'Severe PMS symptoms' },
  { name: 'Hidradenitis Suppurativa', description: 'Chronic skin condition with lumps' },
  { name: 'Costochondritis', description: 'Chest wall inflammation' },
  { name: 'Chronic Inflammation', description: 'Long-term inflammatory response' },
  { name: 'Food Sensitivities', description: 'Adverse reactions to certain foods' },
  { name: 'Mold Sensitivity', description: 'Reactions to mold exposure' },
  { name: 'Chemical Sensitivities', description: 'Reactions to chemicals or fragrances' },
  { name: 'Tension Headaches', description: 'Mild to moderate head pain' },
  { name: 'Cluster Headaches', description: 'Severe headaches in clusters' },
  { name: 'Occipital Neuralgia', description: 'Nerve pain in back of head' },
  { name: 'Trigeminal Neuralgia', description: 'Facial nerve pain' },
  { name: 'Peripheral Neuropathy', description: 'Nerve damage causing numbness' },
  { name: 'Guillain-Barré Syndrome', description: 'Immune system attacks nerves' },
  { name: 'Myasthenia Gravis', description: 'Muscle weakness disorder' },
  { name: 'Narcolepsy', description: 'Excessive daytime sleepiness' },
  { name: 'Chronic Hives', description: 'Recurring itchy welts on skin' },
  { name: 'Angioedema', description: 'Swelling under the skin' },
  { name: 'Dry Eye Syndrome', description: 'Insufficient tear production' },
  { name: 'Floaters', description: 'Spots in vision' },
  { name: 'Light Sensitivity', description: 'Discomfort from light exposure' },
  { name: 'Sound Sensitivity', description: 'Discomfort from noise' },
  { name: 'Temperature Sensitivity', description: 'Difficulty regulating body temperature' },
  { name: 'Cold Intolerance', description: 'Excessive sensitivity to cold' },
  { name: 'Heat Intolerance', description: 'Excessive sensitivity to heat' },
  { name: 'Exercise Intolerance', description: 'Difficulty tolerating physical activity' },
  { name: 'Post-Exertional Malaise', description: 'Worsening symptoms after exertion' },
  { name: 'Orthostatic Intolerance', description: 'Difficulty standing upright' },
  { name: 'Blood Pooling', description: 'Blood collecting in lower body' },
  { name: 'Chest Pain', description: 'Discomfort in chest area' },
  { name: 'Shortness of Breath', description: 'Difficulty breathing' },
  { name: 'Lightheadedness', description: 'Feeling faint or woozy' },
  { name: 'Shakiness', description: 'Trembling or shaking' },
  { name: 'Sweating Issues', description: 'Abnormal sweating patterns' },
  { name: 'Flushing', description: 'Sudden redness of skin' },
  { name: 'Bloating', description: 'Swollen or full feeling in abdomen' },
  { name: 'Constipation', description: 'Difficulty passing stool' },
  { name: 'Diarrhea', description: 'Loose or watery stools' },
  { name: 'Abdominal Pain', description: 'Stomach or belly pain' },
  { name: 'Loss of Appetite', description: 'Reduced desire to eat' },
  { name: 'Weight Changes', description: 'Unexplained weight gain or loss' },
  { name: 'Hair Loss', description: 'Excessive shedding or thinning' },
  { name: 'Brittle Nails', description: 'Weak, breaking nails' },
  { name: 'Dry Skin', description: 'Lack of moisture in skin' },
  { name: 'Skin Rashes', description: 'Red, irritated skin areas' },
  { name: 'Acne', description: 'Pimples and skin blemishes' },
  { name: 'Mouth Sores', description: 'Painful lesions in mouth' },
  { name: 'Dry Mouth', description: 'Lack of saliva production' },
  { name: 'Swollen Lymph Nodes', description: 'Enlarged lymph glands' },
  { name: 'Sore Throat', description: 'Pain or irritation in throat' },
  { name: 'Jaw Pain', description: 'Discomfort in jaw area' },
  { name: 'Neck Pain', description: 'Pain in neck region' },
  { name: 'Shoulder Pain', description: 'Discomfort in shoulders' },
  { name: 'Hip Pain', description: 'Pain in hip joints' },
  { name: 'Knee Pain', description: 'Discomfort in knees' },
  { name: 'Ankle Pain', description: 'Pain in ankle joints' },
  { name: 'Foot Pain', description: 'Discomfort in feet' },
  { name: 'Hand Pain', description: 'Pain in hands or fingers' },
  { name: 'Wrist Pain', description: 'Discomfort in wrists' },
  { name: 'Elbow Pain', description: 'Pain in elbow joints' },
  { name: 'Numbness', description: 'Loss of sensation' },
  { name: 'Tingling', description: 'Pins and needles sensation' },
  { name: 'Burning Sensation', description: 'Feeling of heat on skin' },
  { name: 'Itching', description: 'Desire to scratch' },
  { name: 'Muscle Weakness', description: 'Reduced muscle strength' },
  { name: 'Muscle Cramps', description: 'Involuntary muscle contractions' },
  { name: 'Muscle Twitching', description: 'Involuntary muscle movements' },
  { name: 'Coordination Issues', description: 'Difficulty with movement coordination' },
  { name: 'Balance Problems', description: 'Difficulty maintaining balance' },
  { name: 'Vision Changes', description: 'Alterations in eyesight' },
  { name: 'Blurred Vision', description: 'Unclear or fuzzy vision' },
  { name: 'Double Vision', description: 'Seeing two images' },
  { name: 'Hearing Loss', description: 'Reduced ability to hear' },
  { name: 'Ear Pain', description: 'Discomfort in ears' },
  { name: 'Congestion', description: 'Blocked nasal passages' },
  { name: 'Runny Nose', description: 'Excessive nasal discharge' },
  { name: 'Sneezing', description: 'Frequent sneezing episodes' },
  { name: 'Coughing', description: 'Persistent cough' },
  { name: 'Wheezing', description: 'Whistling sound when breathing' },
  { name: 'Hoarseness', description: 'Raspy or strained voice' },
  { name: 'Difficulty Swallowing', description: 'Trouble with swallowing' },
  { name: 'Feeling of Lump in Throat', description: 'Sensation of obstruction' },
  { name: 'Difficulty Concentrating', description: 'Trouble focusing attention' },
  { name: 'Memory Issues', description: 'Problems with recall' },
  { name: 'Confusion', description: 'Difficulty thinking clearly' },
  { name: 'Mood Swings', description: 'Rapid emotional changes' },
  { name: 'Irritability', description: 'Easily annoyed or angered' },
  { name: 'Emotional Sensitivity', description: 'Heightened emotional responses' },
  { name: 'Feeling Overwhelmed', description: 'Difficulty coping with demands' },
  { name: 'Low Motivation', description: 'Lack of drive or interest' },
  { name: 'Restlessness', description: 'Inability to relax' },
  { name: 'Nightmares', description: 'Disturbing dreams' },
  { name: 'Night Sweats', description: 'Excessive sweating during sleep' },
  { name: 'Frequent Urination', description: 'Urinating often' },
  { name: 'Urgent Urination', description: 'Sudden need to urinate' },
  { name: 'Painful Urination', description: 'Discomfort when urinating' },
  { name: 'Reduced Libido', description: 'Decreased sexual desire' },
  { name: 'Sexual Dysfunction', description: 'Problems with sexual function' },
  { name: 'Menstrual Irregularities', description: 'Unpredictable periods' },
  { name: 'Heavy Periods', description: 'Excessive menstrual bleeding' },
  { name: 'Painful Periods', description: 'Severe menstrual cramps' },
  { name: 'Spotting', description: 'Light bleeding between periods' },
  { name: 'Hot Flashes', description: 'Sudden feeling of warmth' },
  { name: 'Night Chills', description: 'Feeling cold at night' },
  { name: 'Mood Changes (Hormonal)', description: 'Emotional shifts from hormones' },
];

export function searchConditions(query: string): typeof COMMON_CONDITIONS {
  if (!query.trim()) {
    return COMMON_CONDITIONS;
  }

  const lowerQuery = query.toLowerCase();
  return COMMON_CONDITIONS.filter(
    (condition) =>
      condition.name.toLowerCase().includes(lowerQuery) ||
      condition.description.toLowerCase().includes(lowerQuery)
  );
}
